[package]
name = "embeded-td"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed = { version = "6.4.1", features = ["interpolate-folder-path", "include-exclude", "include-flate"] }
tempfile = "3.3.0"
thiserror = "1.0.35"

serde = { version = "1.0.144", features = ["derive"] }
k256 = "0.11.5"
base64 = "0.13.0"
hex = "0.4.3"
ripemd = "0.1.2"
rand_core = "0.6.4"

[features]
default = ["td_ver_0_34"]
td_ver_0_34 = []

[build-dependencies]
flate2 = "1.0.24"
hex = "0.4.3"
reqwest = { version = "0.11.11", features = ["blocking"] }
sha2 = "0.10.6"
tar = "0.4.38"

[dev-dependencies]
rand = "0.8.5"
serde_json = "1.0.85"

