[package]
name = "embeded-td"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed = { version = "6.4.1", features = ["interpolate-folder-path", "include-exclude", "include-flate"] }
tempfile = "3.3.0"
thiserror = "1.0.35"

[features]
default = ["td_ver_0_34"]
td_ver_0_34 = []

[build-dependencies]
flate2 = "1.0.24"
reqwest = { version = "0.11.11", features = ["blocking"] }
tar = "0.4.38"
